Change All Bigint Ref
mariadb-corporation/mariadb-connector-nodejs pull request #143
Opened 2020-12-30 19:30 UTC by rpsoftech

While Compiling It with some old library line @ziet/ncc

(node:9454) UnhandledPromiseRejectionWarning: Error: Module parse failed: Identifier directly after number (669:86)

2021-01-11 09:21 UTC, rusher commented
This is normally not an issue, because node.js support bigint for all supported version (and if not supported, an error message is thrown).
Could you indicate the node.js version you are using ?

2021-01-12 09:04 UTC, rpsoftech commented
it was not thrown by nodejs.

It was by webpack while compiling nodejs code to singal file.

2021-01-14 17:58 UTC, rusher requested changes
Ok, i didn't understand initial concern: Bigint literal are not supported by webpack. 
So this changed can make sense. Tests are just to be corrected accordingly

2021-01-14 17:58 UTC, rusher commented on test/integration/datatype/test-integer.js
> +        assert.strictEqual(rows[4].v, BigInt(9007199254740992));
BigInt(9007199254740992) is unpredicable  that has to be replaced by string -> BigInt('9007199254740992')

2021-01-14 17:58 UTC, rusher commented on test/integration/datatype/test-integer.js
> +        assert.strictEqual(rows[5].v, BigInt(9007199254740993));
same here BigInt(9007199254740993) => BigInt('9007199254740993')

2021-01-14 17:58 UTC, rusher commented on test/integration/datatype/test-integer.js
> +            assert.strictEqual(rows.insertId, BigInt(9007199254740994));
BigInt('9007199254740994')

2021-01-14 17:58 UTC, rusher commented on test/integration/datatype/test-integer.js
> +    const maxValue = BigInt(18446744073709551615);
BigInt('18446744073709551615')

2021-01-18 11:43 UTC, rusher commented
Thanks for correcting test. 
This is now merged in develop branch, and will be release in next 2.5.3 version

2021-01-18 11:43 UTC, closed without merging